### ISSUE TITLE
Bug in Ushahidi Android App (ver. 3.1.5) - pic attachment

### ISSUE THREAD

**Issue by dafe75** [ushahidi/Ushahidi_Android#120] opened 2013-04-17 13:32 UTC
**Steps to reproduce the bug**
1. Upload a report with a picture attached via the Android App for Ushahidi (ver. 3.1.5);
2. Close the app;
3. Re-open the app while the report hasn't been approved by the deployment administrator yet;
4. The report is uploaded to the system again with no limit (that is, if you re-open the app 4 times you’ll have the same report uploaded 4 times).

_As mentioned in step 1 the report must has a picture attached; the bug doesn't turn up if no picture is attached._

**Comment by manwinder** [comment] 2013-04-21 08:17
There is another problem that I noticed with regards to reports submitted from Mobile (Android) App. 3.1.5

A) The same problem (as mentioned above) is observed even when the mobile app crashes.
i.e. you upload a report - it is pending for upload - app stops - you reopen the app thinking report would not have uploaded. But the report gets uploaded as many times as you reopen the app.

![Upload failure in mobile but reports syncd multiple times](https://f.cloud.github.com/assets/3960883/406113/d6a1c104-aa5b-11e2-8e07-d5577faf01b0.png)

B) Also each category is displayed thrice in the mobile app (Second attachment)

![Screenshot_2013-04-19-20-32-36](https://f.cloud.github.com/assets/3960883/406112/d6571492-aa5b-11e2-9fc4-b56fd1b4713b.png)

**Comment by eyedol** [comment] 2013-04-21 10:59
@manwinder could you include your URL so I can test.

**Comment by manwinder** [comment] 2013-04-21 11:01
@eyedol @elleespere 

https://indiaoye.crowdmap.com

**Comment by manwinder** [comment] 2013-04-21 11:08
@elle-espere got your spellings wrong. FYIP

**Comment by eyedol** [comment] 2013-04-23 00:13
@dafe75  and @manwinder. Fixed. I'll make an apk available for testing to confirm it works from your end.

**Comment by manwinder** [comment] 2013-04-23 14:53
@eyedol @elle-espere

hasn't improved for me
the categories still display in triplicate (PFA)

The reports are also getting uploaded every time I open the app and the
application crashes

![Screenshot_2013-04-23-20-11-02](https://f.cloud.github.com/assets/3960883/415116/89a08954-ac2b-11e2-93c6-749b3cf80062.png)
![repetitive reports](https://f.cloud.github.com/assets/3960883/415122/9c476118-ac2b-11e2-9c09-3320093170b2.png)

**Comment by eyedol** [comment] 2013-04-23 23:54
@manwinder  are you running the latest code from `develop` ?

**Comment by manwinder** [comment] 2013-04-24 01:38
@eyedol  @elle-espere 
please guide me how can I ensure that I am using the latest code.

I use crowdmap and my mobile app is updated to the latest.

**Comment by ghost** [comment] 2013-04-26 03:13
@eyedol was not able to reproduce error with updated code.   @dafe75  @manwinder

**Comment by eyedol** [comment] 2013-04-26 15:25
@elle-espere  Glad to hear. Closing this issue.

**Closed as completed by eyedol** 2013-04-26 15:25 UTC

**Comment by manwinder** [comment] 2013-04-26 18:07
@eyedol @elle-espere As requested earlier, can you please guide me with the updated code ?

There is no improvement at my end !

**Comment by eyedol** [comment] 2013-04-27 09:16
@manwinder Read this guide https://wiki.ushahidi.com/display/WIKI/Build+The+Android+App

**Comment by manwinder** [comment] 2013-04-28 06:46
@eyedol @elle-espere Thanks for the guide.
I am not a techie / developer. So just relied on the latest version (3.1.5) that was available on the play store last time.
I couldn't find any new update available on the play store. Won't the improvement mentioned above be a part of the new release ? If yes, when is the new release.

Thank you and please excuse me for my 'technical' ignorance.

**Comment by ghost** [comment] 2013-05-03 00:04
@manwinder please excuse me not replying earlier.  Will send you an email.
