### ISSUE TITLE
Deployment does not show in android device when going to "Find Maps Arround Me"

### ISSUE THREAD

**Issue by EUNACAL** [ushahidi/Ushahidi_Android#106] opened 2012-12-10 16:04 UTC
I have set up an ushahidi deployment. I try to access it from my android device going to "Find Maps Arround Me" but the deployment does not show. Any idea why?

**Comment by GemmaNash** [comment] 2013-01-25 09:41
So this is the same issue I have... does anyone know how to fix it? Thanks!

**Comment by eyedol** [comment] 2013-02-02 07:00
@EUNACAL Did you have public listing enabled at the ushahidi backend? It has be enabled before the deployment shows up on the backend. Since this is not a bug, I'm going to close this issue. We can have further discussion on the [forums](forums.ushahidi.com)

**Closed as completed by eyedol** 2013-02-02 07:00 UTC

**Comment by GemmaNash** [comment] 2013-02-04 09:22
Hi
Yes, our listing is public on crowdmap.
Gemma
