### ISSUE TITLE
Unable to build using ADT several errors (see comment)

### ISSUE THREAD

**Issue by stefanosc** [ushahidi/Ushahidi_Android#115] opened 2013-04-03 22:34 UTC
Hello and thank you for the awesome work.
disclaimer: I am new to android dev and I am just learning so I may be missing something, please bear with me and let me know anything.

So I downloaded the repository as a zip and imported the "core" project.
I followed all the steps in BUILDING.txt
I added the libraries needed, and I am targeting 4.2.2 at the moment (I tried various versions of 4.xx)

I get the following errors:

In styles:
Description Resource    Path    Location    Type
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock'.    styles.xml  /Core/res/values    line 16 Android AAPT Problem
error: Error: No resource found that matches the given name: attr 'actionBarTabStyle'.  styles.xml  /Core/res/values    line 18 Android AAPT Problem
error: Error retrieving parent for item: No resource found that matches the given name 'Widget.Sherlock.Light.ActionBar.TabView'.   styles.xml  /Core/res/values    line 22 Android AAPT Problem
error: Error: No resource found that matches the given name: attr 'selectableItemBackground'.   styles.xml  /Core/res/values    line 17 Android AAPT Problem

In Strings:
Description Resource    Path    Location    Type
error: Resource entry hint_total_reports is already defined.    strings.xml /Core/res/values-mk line 229    Android AAPT Problem
error: Resource entry hint_total_reports is already defined.    strings.xml /Core/res/values    line 250    Android AAPT Problem
error: Resource entry choose_categories is already defined. strings.xml /Core/res/values-ko line 211    Android AAPT Problem
error: Resource entry choose_categories is already defined. strings.xml /Core/res/values-de line 215    Android AAPT Problem
error: Resource entry no_reports is already defined.    strings.xml /Core/res/values    line 251    Android AAPT Problem
error: Resource entry hint_phonenumber is already defined.  strings.xml /Core/res/values-ko line 222    Android AAPT Problem
error: Resource entry hint_phonenumber is already defined.  strings.xml /Core/res/values-de line 226    Android AAPT Problem
error: Resource entry hint_total_reports is already defined.    strings.xml /Core/res/values-ko line 224    Android AAPT Problem
error: Resource entry choose_categories is already defined. strings.xml /Core/res/values-mk line 216    Android AAPT Problem
error: Resource entry hint_total_reports is already defined.    strings.xml /Core/res/values-de line 228    Android AAPT Problem
error: Resource entry no_reports is already defined.    strings.xml /Core/res/values-ko line 225    Android AAPT Problem
error: Resource entry no_reports is already defined.    strings.xml /Core/res/values-de line 229    Android AAPT Problem
error: Resource entry hint_phonenumber is already defined.  strings.xml /Core/res/values-mk line 227    Android AAPT Problem
error: Resource entry hint_phonenumber is already defined.  strings.xml /Core/res/values    line 248    Android AAPT Problem

And many other strings errors.

Finally I get:
Description Resource    Path    Location    Type
The type android.support.v4.view.MenuItem cannot be resolved. It is indirectly referenced from required .class files    MapFragment.java    /Core/src/com/ushahidi/android/app/ui/tablet    line 1  Java Problem
The project was not built since its build path is incomplete. Cannot find the class file for android.support.v4.view.MenuItem. Fix the build path then try building this project    Core        Unknown Java Problem

I tried various things, adding different JAR files to the build path, targeting different android versions, I am unable to find a solution.

Would anyone be able to clarify the issue?

thank you very much.

**Comment by eyedol** [comment] 2013-04-04 00:15
@stefanonyn This is not a bug. I would rather open an issue for improvement to documentation. Let's take this to the forums. I'm going to go ahead and close this.

**Closed as completed by eyedol** 2013-04-04 00:15 UTC

**Comment by stefanosc** [comment] 2013-04-04 21:14
Thanks so much, I posted on the forum
http://forums.ushahidi.com/forums/topic/unable-to-build-using-adt-several-errors/
